apiVersion: v2
appVersion: 2.17.0
description: A Helm chart for multicluster-engine
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-217@sha256:9cc9a80ab604a3dbeb350df5548e1e87f7b07c7e98692156fcfa63201b657c68
type: application
version: 2.17.0
